resources:
- ../../base/istory-app
- ../../base/istory-db

namespace: istory-dev

patches:
- path: patch-lb-annotations.yml
  target:
    kind: Service
    name: istory-app-lb
- path: patch-deploy.yml
  target:
    kind: Deployment
    name: istory-app-deploy
images:
- name: istory
  newName: dangtong76/istory
  newTag: "15"
generatorOptions:
  disableNameSuffixHash: true
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
